# IFC FY24 Financials Dataclass
# Generated by the research agent on 2026-08-03 16:28 UTC.
# --- ifc_financials_fy24.py ---
from dataclasses import dataclass
from typing import ClassVar

@dataclass(frozen=True)
class IFCFY24Financials:
    """
    Dataclass holding selected financial indicators for the International Finance Corporation (IFC) 
    for the fiscal year ended June 30, 2024 (FY24).
    
    Figures are presented in millions of US dollars (US$ in millions) as reported in the official 
    IFC 2024 Annual Report financial statements.
    """
    # Net income (loss) for FY24: $1,485 million
    # Source: Consolidated Statements of Operations (Page 64)
    net_income_usd_millions: float = 1485.0
    
    # Total assets as of June 30, 2024: $108,187 million
    # Source: Consolidated Balance Sheets (Page 63)
    total_assets_usd_millions: float = 108187.0
    
    # Metadata and Citations
    NET_INCOME_CITATION: ClassVar[str] = (
        "IFC Annual Report 2024 Financial Statements, Consolidated Statements of Operations, Page 64"
    )
    TOTAL_ASSETS_CITATION: ClassVar[str] = (
        "IFC Annual Report 2024 Financial Statements, Consolidated Balance Sheets, Page 63"
    )

    def display_summary(self) -> None:
        """Prints a human-readable summary of the financials."""
        print("IFC FY24 Financial Performance:")
        print(f"  Net Income:   ${self.net_income_usd_millions:,.2f} million "
              f"(${self.net_income_usd_millions / 1000.0:.3f} billion)")
        print(f"  Total Assets: ${self.total_assets_usd_millions:,.2f} million "
              f"(${self.total_assets_usd_millions / 1000.0:.3f} billion)")
        print("\nSources:")
        print(f"  - Net Income: {self.NET_INCOME_CITATION}")
        print(f"  - Total Assets: {self.TOTAL_ASSETS_CITATION}")

if __name__ == "__main__":
    financials = IFCFY24Financials()
    financials.display_summary()

# Sources:
#   data/raw/ifc-annual-report-2024-financials.pdf, Page 63
#   data/raw/ifc-annual-report-2024-financials.pdf, Page 64
